development: &default
  adapter: postgresql
  database: blog_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: blog_test

production: &deploy
  encoding: utf8
  database: blog_production
  min_messages: warning
  pool: 5
  timeout: 5000